const MAX_PARTITION_KEY_LENGTH = 256;
const TRIVIAL_PARTITION_KEY = "0";
const CRYPTO_ALGORITHM = "sha3-512";

module.exports = {
  MAX_PARTITION_KEY_LENGTH,
  TRIVIAL_PARTITION_KEY,
  CRYPTO_ALGORITHM,
};
